[package]
name = "marinade-sdk-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "fold"] }
quote = "1.0"
proc-macro2 = "1.0"
log = "0.4"

[dev-dependencies]
borsh = "0.10"
is_trait = "0.1.4"
micro-anchor = { path = "../../libs/micro-anchor" }
solana-account-info = "2.3"
solana-instruction = "2.3"
solana-pubkey = "2.3"
solana-sdk-ids = "2.2"
