[package]
name = "marinade-sdk"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
name = "marinade_sdk"

[features]

[profile.release]
overflow-checks = true

[dependencies]
borsh = { version = "1.6.1", features = ["derive", "unstable__schema"] }
derive_more = "0.99.17"
micro-anchor = { path = "../../libs/micro-anchor" }
marinade-sdk-macro = { path = "../../libs/marinade-sdk-macro" }
solana-program = "4.0.0"
solana-pubkey = { version = "4.2.0", features = ["borsh"] }
solana-sdk-ids = "3.1.0"
solana-stake-interface = "3.1.0"
spl-token = { version = "9.0.0", features = ["no-entrypoint"] }
