[package]
name = "micro-anchor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program-entrypoint = "2.3"
solana-instruction = "2.3"
solana-account-info = "2.3"
solana-pubkey = "2.3"
solana-cpi = "2.2"
borsh = "0.10"
derive_more = { version = "2.0", features = ["display", "error"] }
